[package]
name = "chimp-explorer"
version = "0.1.0"
authors = ["Stef Robbe <stef.robbe@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
bdays = "0.1.3"
chrono = "0.4.38"
crossterm = "0.27.0"
ratatui = "0.26.0"
serde = "1.0.198"
serde_derive = "1.0.198"
serde_json = "1.0.116"
